language: python
sudo: false

notifications:
  on_success: change
  on_failure: always

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=lint
  - python: nightly
    env: TOXENV=py37
  allow_failures:
  - env: TOXENV=py37

install:
- travis_retry pip install -U setuptools pip tox

script:
- travis_retry tox
